apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: crossplane-objectstorage
  annotations:
    # Set the annotations defining the maintainer, source, license, and description of your Configuration
    meta.crossplane.io/maintainer: Deine Mudda dm@somemail.xyz
    meta.crossplane.io/source: github.com/quercus-carsten/objectstorage-composition
    # Set the license of your Configuration
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: |
      Crossplane Configuration delivering CRDs to provision s3 buckets.
    meta.crossplane.io/readme: |
      It's a Nested Composition.
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v1.3.0"
  crossplane:
    version: ">=v1.15.1-0"
